### ISSUE TITLE
Connections to `api.themoviedb.org` refused - brand new Jellyfin installation

### ISSUE THREAD

**Issue by ndom91** [jellyfin/jellyfin-plugin-tmdb#29]
Hi Team,

I've got a brand new jellyfin installation and have `TMDb` setup as a metadata source for some of the TV Show library options.

Scanning the library is always stuck at `72.2%` and the jellyfin logs at `/var/log/jellyfin/*` are full of messages like

```
[2023-02-25 16:49:23.979 +00:00] [ERR] Error processing request. URL "GET" "/tmdb/ClientConfiguration".
System.Net.Http.HttpRequestException: Connection refused (api.themoviedb.org:443)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)

```

I've checked my DNS server logs, it does seem to resolve, and I couldn't find an option to enter a new API key or anything like that. So not sure what could be leading to failed tmdb calls.

**Comment by ndom91** [comment]
Edit: nevermind, it resolved to `127.0.0.1` on that server for some reason. Manually adding some of the servers to `/etc/hosts` fixed it. Closing
